name: daily

on:
  push:
    branches: [main]

jobs:
  doc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20.3.0"

      - name: Enable Corepack
        run: corepack enable
      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate
      - name: Install Node modules
        run: pnpm install
      - name: Build app
        run: pnpm bld
      - name: Publish app to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm exe -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
